Model GAP_hcp_hess, Test phonon_hpc
Test run at 2018-10-10 16:37

model file: ../../../models/Ti/GAP_hcp_hess/model.py
============================================================
import os

from quippy import Potential
import __builtin__

orig_dir = os.getcwd()
model_dir = os.path.dirname(__file__)
if model_dir != '':
    os.chdir(model_dir)

if os.path.exists('gp_iter6_sparse9k.xml.sparseX.GAP_2017_6_17_60_4_3_56_1651.bz2'):
    os.system('bunzip2 gp_iter6_sparse9k.xml.sparseX.GAP_2017_6_17_60_4_3_56_1651.bz2')

try:
    if hasattr(__builtin__, 'mpi_glob'):
        calculator = Potential(init_args='Potential xml_label="GAP_2018_6_26_60_20_15_36_820"',
                                               param_filename='gp_4b_no_wire_surface.xml', mpi_obj=mpi_glob)
    else:
        calculator = Potential(init_args='Potential xml_label="GAP_2018_10_10_60_16_34_13_754"', param_filename='gp_4b_hcp_hes_train_scale.xml')
    Potential.__str__ = lambda self: '<GAP Potential>'
finally:
    os.chdir(orig_dir)

no_checkpoint = True

name = 'GAP'
============================================================
test file: ../../../tests/Ti/phonon_hpc/test.py
============================================================
Traceback (most recent call last):
  File "run-model-test-cas.py", line 88, in <module>
    sys.stdout.write(open(test_file).read())
IOError: [Errno 2] No such file or directory: '../../../tests/Ti/phonon_hpc/test.py'
